"""Models for the Mastermind game.

This module defines the models for the Mastermind game,
including the secret code, guess, feedback, and analysis.
"""

from typing import List, Literal

from pydantic import BaseModel, Field

# Define valid Mastermind colors
ValidColor = Literal["red", "blue", "green", "yellow", "purple", "orange"]


class ColorCode(BaseModel):
    """Represents the secret code generated by the codemaker.

    This class defines the structure of the secret code, which is a list of 4 colors
    chosen from a predefined set of valid colors.
    """

    code: List[ValidColor] = Field(
        ...,
        min_items=4,
        max_items=4,
        description="The secret code: 4 colors chosen from the allowed set",
    )


class MastermindGuess(BaseModel):
    """Represents a guess in Mastermind.

    This class defines the structure of a guess, which is a list of 4 colors
    chosen from a predefined set of valid colors.
    """

    colors: List[ValidColor] = Field(
        ..., min_items=4, max_items=4, description="List of 4 colors"
    )
    player: Literal["player1", "player2"] = Field(
        ..., description="Player making the guess"
    )

    def __str__(self):
        return f"{self.player} guesses: {', '.join(self.colors)}"


class MastermindFeedback(BaseModel):
    """Feedback for a Mastermind guess.

    This class defines the structure of feedback for a guess in Mastermind,
    which includes the number of pegs with correct color and position,
    and the number of pegs with correct color but wrong position.
    """

    correct_position: int = Field(
        ..., ge=0, le=4, description="Number of pegs with correct color and position"
    )
    correct_color: int = Field(
        ...,
        ge=0,
        le=4,
        description="Number of pegs with correct color but wrong position",
    )

    def __str__(self):
        return f"🌟 Correct position: {self.correct_position}, 🔄 Correct color: {self.correct_color}"

    def is_winning(self) -> bool:
        """Check if this feedback indicates a win (all 4 pegs in correct position)."""
        return self.correct_position == 4


class MastermindAnalysis(BaseModel):
    """Analysis of a Mastermind position.

    This class defines the structure of an analysis for a Mastermind position,
    which includes the estimated number of possible combinations left,
    the colors with high probability of being in the solution,
    the recommended next guess,
    the colors likely eliminated,
    and the fixed positions.
    """

    possible_combinations: int = Field(
        ..., description="Estimated number of possible combinations left"
    )
    high_probability_colors: List[ValidColor] = Field(
        ..., description="Colors with high probability of being in the solution"
    )
    eliminated_colors: List[ValidColor] = Field(
        default_factory=list, description="Colors likely eliminated"
    )

    fixed_positions: List[dict[str, ValidColor]] = Field(
        default_factory=list,
        description="List of fixed positions as dicts like {'index': 'color'}",
    )

    strategy: str = Field(..., description="Current strategy recommendation")
    reasoning: str = Field(..., description="Detailed reasoning for the analysis")
    confidence: int = Field(
        ..., ge=1, le=10, description="Confidence level in this analysis (1-10)"
    )
