"""
Battleship game implementation for AI agents.

This package provides a complete implementation of a two-player Battleship
game with LLM-powered agents, including:
    - Game state management and ship placement
    - LLM-based targeting strategies
    - Turn-based gameplay mechanics
    - Configurable board sizes and ship layouts
    - Detailed game history and move tracking

The implementation uses LangGraph for workflow management and supports
multiple LLM providers (Azure, OpenAI, Anthropic) for agent decisions.

Components:
    BattleshipAgent:
        Main agent class managing the game flow, player interactions,
        and game state transitions.

    BattleshipState:
        Tracks the current game state including board positions,
        ship placements, and game phase.

    BattleshipAgentConfig:
        Configuration class for customizing game parameters like
        board size, fleet composition, and player settings.

    Models:
        Ship: Represents a battleship with size, position, and health.
        Coordinates: (row, col) position on the board.
        MoveCommand: A player's targeting decision.
        Analysis: Strategic output generated by an LLM.
        ShipPlacement: LLM-generated placement of a single ship.
        ShipPlacementListModel: Full list of ship placements (RootModel).
        MoveOutcome: Result of a move (hit, miss, sunk).

    Prompts:
        generate_ship_placement_prompt:
            Creates LLM prompt for strategic ship placement.
        generate_move_prompt:
            Creates LLM prompt for targeting decision.
        generate_analysis_prompt:
            Creates LLM prompt for board evaluation.

    Engines:
        build_battleship_engines:
            LLM engine configurations for ship placement, moves, and analysis.

Example:
    >>> from haive_agents.agent_games.battleship import BattleshipAgent, BattleshipAgentConfig
    >>> agent = BattleshipAgent(BattleshipAgentConfig())
    >>> result = agent.run()
"""

from .agent import BattleshipAgent
from .config import BattleshipAgentConfig
from .state import BattleshipState
from .state_manager import BattleshipStateManager
from .models import (
    Analysis,
    Coordinates,
    MoveCommand,
    MoveOutcome,
    Ship,
    ShipPlacement,
    ShipPlacementWrapper,
    GamePhase,
    PlayerBoard
)
from .prompts import (
    generate_ship_placement_prompt,
    generate_move_prompt,
    generate_analysis_prompt
)
from .engines import build_battleship_engines

__all__ = [
    # Core components
    'BattleshipAgent',
    'BattleshipAgentConfig',
    'BattleshipState',
    'BattleshipStateManager',

    # Models
    'Ship',
    'Coordinates',
    'MoveCommand',
    'MoveOutcome',
    'ShipPlacement',
    'ShipPlacementWrapper',
    'Analysis',
    'GamePhase',
    'PlayerBoard',

    # Prompts
    'generate_ship_placement_prompt',
    'generate_move_prompt',
    'generate_analysis_prompt',

    # Engines
    'build_battleship_engines'
]

__version__ = '1.0.0'
